#pragma once
#include <string>
#include <vector>
#include <unordered_map>
#include <array>

struct SkinEntry {
    int paint_kit;
    const char* name;
};

// Weapon item definition indices (from CS2 schema).
enum WeaponID : int {
    WEAPON_DEAGLE = 1,
    WEAPON_ELITE = 2,
    WEAPON_FIVESEVEN = 3,
    WEAPON_GLOCK = 4,
    WEAPON_AK47 = 7,
    WEAPON_AUG = 8,
    WEAPON_AWP = 9,
    WEAPON_FAMAS = 10,
    WEAPON_G3SG1 = 11,
    WEAPON_GALIL = 13,
    WEAPON_M249 = 14,
    WEAPON_M4A4 = 16,
    WEAPON_MAC10 = 17,
    WEAPON_P2000 = 32,
    WEAPON_MP5SD = 23,
    WEAPON_UMP45 = 24,
    WEAPON_XM1014 = 25,
    WEAPON_PPBIZON = 26,
    WEAPON_MAG7 = 27,
    WEAPON_NEGEV = 28,
    WEAPON_SAWEDOFF = 29,
    WEAPON_TEC9 = 30,
    WEAPON_P250 = 36,
    WEAPON_MP7 = 33,
    WEAPON_MP9 = 34,
    WEAPON_NOVA = 35,
    WEAPON_P90 = 19,
    WEAPON_SCAR20 = 38,
    WEAPON_SG553 = 39,
    WEAPON_SSG08 = 40,
    WEAPON_M4A1S = 60,
    WEAPON_USP = 61,
    WEAPON_CZ75 = 63,
    WEAPON_REVOLVER = 64,
    WEAPON_KNIFE_BAYONET = 500,
    WEAPON_KNIFE_FLIP = 505,
    WEAPON_KNIFE_GUT = 506,
    WEAPON_KNIFE_KARAMBIT = 507,
    WEAPON_KNIFE_M9 = 508,
    WEAPON_KNIFE_HUNTSMAN = 512,
    WEAPON_KNIFE_FALCHION = 514,
    WEAPON_KNIFE_BOWIE = 515,
    WEAPON_KNIFE_BUTTERFLY = 516,
    WEAPON_KNIFE_SHADOW = 517,
    WEAPON_KNIFE_STILETTO = 518,
    WEAPON_KNIFE_TALON = 519,
    WEAPON_KNIFE_SKELETON = 520,
    WEAPON_KNIFE_KUKRI = 521,
};

namespace SkinDB {

struct WeaponInfo {
    const char* display_name;
    int default_paint_kit;  // 0 = default skin
};

inline const std::unordered_map<int, WeaponInfo>& Weapons() {
    static const std::unordered_map<int, WeaponInfo> w = {
        { WEAPON_DEAGLE,      { "Desert Eagle", 0 } },
        { WEAPON_ELITE,       { "Dual Berettas", 0 } },
        { WEAPON_FIVESEVEN,   { "Five-SeveN", 0 } },
        { WEAPON_GLOCK,       { "Glock-18", 0 } },
        { WEAPON_AK47,        { "AK-47", 0 } },
        { WEAPON_AUG,         { "AUG", 0 } },
        { WEAPON_AWP,         { "AWP", 0 } },
        { WEAPON_FAMAS,       { "FAMAS", 0 } },
        { WEAPON_G3SG1,       { "G3SG1", 0 } },
        { WEAPON_GALIL,       { "Galil AR", 0 } },
        { WEAPON_M249,        { "M249", 0 } },
        { WEAPON_M4A4,        { "M4A4", 0 } },
        { WEAPON_MAC10,       { "MAC-10", 0 } },
        { WEAPON_P2000,       { "P2000", 0 } },
        { WEAPON_MP5SD,       { "MP5-SD", 0 } },
        { WEAPON_UMP45,       { "UMP-45", 0 } },
        { WEAPON_XM1014,      { "XM1014", 0 } },
        { WEAPON_PPBIZON,     { "PP-Bizon", 0 } },
        { WEAPON_MAG7,        { "MAG-7", 0 } },
        { WEAPON_NEGEV,       { "Negev", 0 } },
        { WEAPON_SAWEDOFF,    { "Sawed-Off", 0 } },
        { WEAPON_TEC9,        { "Tec-9", 0 } },
        { WEAPON_P250,        { "P250", 0 } },
        { WEAPON_MP7,         { "MP7", 0 } },
        { WEAPON_MP9,         { "MP9", 0 } },
        { WEAPON_NOVA,        { "Nova", 0 } },
        { WEAPON_P90,         { "P90", 0 } },
        { WEAPON_SCAR20,      { "SCAR-20", 0 } },
        { WEAPON_SG553,       { "SG 553", 0 } },
        { WEAPON_SSG08,       { "SSG 08", 0 } },
        { WEAPON_M4A1S,       { "M4A1-S", 0 } },
        { WEAPON_USP,         { "USP-S", 0 } },
        { WEAPON_CZ75,        { "CZ75-Auto", 0 } },
        { WEAPON_REVOLVER,    { "R8 Revolver", 0 } },
        { WEAPON_KNIFE_BAYONET,   { "Bayonet", 0 } },
        { WEAPON_KNIFE_FLIP,      { "Flip Knife", 0 } },
        { WEAPON_KNIFE_GUT,       { "Gut Knife", 0 } },
        { WEAPON_KNIFE_KARAMBIT,  { "Karambit", 0 } },
        { WEAPON_KNIFE_M9,        { "M9 Bayonet", 0 } },
        { WEAPON_KNIFE_BUTTERFLY, { "Butterfly Knife", 0 } },
        { WEAPON_KNIFE_SKELETON,  { "Skeleton Knife", 0 } },
        { WEAPON_KNIFE_KUKRI,     { "Kukri Knife", 0 } },
    };
    return w;
}

// ── Per-weapon skin presets ──
// Each weapon maps to a list of { paint_kit, display_name }.
// These are the most commonly used / high-value skins for each weapon.

inline const std::unordered_map<int, std::vector<SkinEntry>>& SkinsByWeapon() {
    static const std::unordered_map<int, std::vector<SkinEntry>> s = {

        // ════════════════════════════════════════════════════════════════
        // RIFLES
        // ════════════════════════════════════════════════════════════════

        { WEAPON_AK47, {
            { 0,    "Default" },
            { 44,   "Red Laminate" },
            { 180,  "Redline" },
            { 302,  "Vulcan" },
            { 747,  "Neon Rider" },
            { 801,  "The Empress" },
            { 44,   "Case Hardened" },
            { 144,  "Fire Serpent" },
            { 226,  "Blue Laminate" },
            { 300,  "Emerald Pinstripe" },
            { 380,  "Wasteland Rebel" },
            { 394,  "Cartel" },
            { 422,  "Elite Build" },
            { 456,  "Hydroponic" },
            { 474,  "Aquamarine Revenge" },
            { 490,  "Frontside Misty" },
            { 506,  "Point Disarray" },
            { 524,  "Fuel Injector" },
            { 639,  "Asiimov" },
            { 878,  "Ice Coaled" },
            { 921,  "Head Shot" },
            { 978,  "Legion of Anubis" },
            { 1000, "Nightwish" },
            { 1038, "Green Laminate" },
            { 1104, "Uncharted" },
            { 1140, "Slate" },
            { 1173, "Bloodsport" },
            { 1191, "Phantom Disruptor" },
        }},

        { WEAPON_AWP, {
            { 0,    "Default" },
            { 38,   "Dragon Lore" },
            { 51,   "Lightning Strike" },
            { 174,  "BOOM" },
            { 181,  "Corticera" },
            { 212,  "Graphite" },
            { 251,  "Pit Viper" },
            { 259,  "Medusa" },
            { 279,  "Asiimov" },
            { 344,  "Hyper Beast" },
            { 395,  "Man-o'-war" },
            { 424,  "Worm God" },
            { 446,  "Sun in Leo" },
            { 475,  "Wildfire" },
            { 525,  "Elite Build" },
            { 662,  "Fade" },
            { 837,  "Neo-Noir" },
            { 898,  "Containment Breach" },
            { 942,  "The Prince" },
            { 979,  "Atheris" },
            { 1010, "Containment Breach" },
            { 1044, "Gungnir" },
            { 1073, "Desert Hydra" },
            { 1105, "Chromatic Aberration" },
            { 1139, "Doodle Lore" },
            { 1168, "Exoskeleton" },
        }},

        { WEAPON_M4A4, {
            { 0,    "Default" },
            { 155,  "Bullet Rain" },
            { 164,  "Modern Hunter" },
            { 167,  "Radiation Hazard" },
            { 255,  "Asiimov" },
            { 309,  "Howl" },
            { 336,  "Desert-Strike" },
            { 384,  "Griffin" },
            { 388,  "Desolate Space" },
            { 400,  "Dragon King" },
            { 449,  "Poseidon" },
            { 471,  "Daybreak" },
            { 480,  "Evil Daimyo" },
            { 488,  "Buzz Kill" },
            { 512,  "Royal Paladin" },
            { 533,  "The Battlestar" },
            { 730,  "Neo-Noir" },
            { 780,  "The Emperor" },
            { 811,  "In Living Color" },
            { 845,  "Spider Lily" },
            { 880,  "Coalition" },
            { 922,  "Temukau" },
            { 975,  "Magnesium" },
            { 1009, "Prinstream" },
            { 1037, "Poly Mag" },
            { 1106, "Afterimage" },
        }},

        { WEAPON_M4A1S, {
            { 0,    "Default" },
            { 60,   "Dark Water" },
            { 77,   "Boreal Forest" },
            { 189,  "Bright Water" },
            { 217,  "Blood Tiger" },
            { 235,  "VariCamo" },
            { 254,  "Nitro" },
            { 257,  "Guardian" },
            { 301,  "Atomic Alloy" },
            { 321,  "Master Piece" },
            { 326,  "Knight" },
            { 360,  "Cyrex" },
            { 383,  "Basilisk" },
            { 430,  "Hyper Beast" },
            { 440,  "Icarus Fell" },
            { 445,  "Hot Rod" },
            { 587,  "Chantico's Fire" },
            { 757,  "Decimator" },
            { 839,  "Player Two" },
            { 844,  "Golden Coil" },
            { 897,  "Printstream" },
            { 958,  "Blue Phosphor" },
            { 974,  "Nightmare" },
            { 1039, "Leaded Glass" },
            { 1103, "Welcome to the Jungle" },
            { 1136, "Atomic Alloy" },
        }},

        { WEAPON_SG553, {
            { 0,    "Default" },
            { 38,   "Bulldozer" },
            { 187,  "Pulse" },
            { 247,  "Tiger Tooth" },
            { 306,  "Cyrex" },
            { 363,  "Fallout Warning" },
            { 428,  "Treq" },
            { 489,  "Tiger Moth" },
            { 598,  "Aloha" },
            { 612,  "Desert Storm" },
            { 842,  "Integrale" },
            { 944,  "Bounty Hunter" },
            { 1108, "Turbine" },
        }},

        { WEAPON_FAMAS, {
            { 0,    "Default" },
            { 22,   "Afterimage" },
            { 77,   "Boreal Forest" },
            { 154,  "Sergeant" },
            { 172,  "Styx" },
            { 196,  "Hexane" },
            { 244,  "Pulse" },
            { 429,  "Meastro" },
            { 493,  "Neural Net" },
            { 627,  "Roll Cage" },
            { 677,  "Compass Rose" },
            { 836,  "Cataclysm" },
            { 919,  "Meltdown" },
            { 1013, "Jamie Fox" },
        }},

        { WEAPON_GALIL, {
            { 0,    "Default" },
            { 39,   "Winter Forge" },
            { 82,   "Forest DDPAT" },
            { 196,  "Chatterbox" },
            { 308,  "Cerberus" },
            { 398,  "Eco" },
            { 460,  "Stone Cold" },
            { 478,  "Tgewater" },
            { 661,  "Aqua Terrace" },
            { 763,  "Orange DDPAT" },
            { 834,  "Soul Rebel" },
            { 862,  "Signal" },
            { 977,  "Connexion" },
            { 1083, "Doppler" },
        }},

        { WEAPON_AUG, {
            { 0,    "Default" },
            { 9,    "Akoben" },
            { 46,   "Stymphalian" },
            { 83,   "Anodized Navy" },
            { 305,  "Torque" },
            { 444,  "Ricochet" },
            { 455,  "Chameleon" },
            { 600,  "Daedalus" },
            { 762,  "Akihabara Accept" },
            { 823,  "Amphibious" },
            { 893,  "Flame Jinn" },
            { 959,  "Sweeper" },
            { 1043, "Heat" },
        }},

        // ════════════════════════════════════════════════════════════════
        // SNIPER RIFLES
        // ════════════════════════════════════════════════════════════════

        { WEAPON_SSG08, {
            { 0,    "Default" },
            { 27,   "Blue Steel" },
            { 59,   "Slaughter" },
            { 60,   "Dark Water" },
            { 99,   "Dragonfire" },
            { 189,  "Bloom" },
            { 222,  "Blood in the Water" },
            { 261,  "Slashed" },
            { 319,  "Detour" },
            { 361,  "Big Iron" },
            { 382,  "Abyssal" },
            { 624,  "Necro Jr" },
            { 670,  "Rattlesnake" },
            { 848,  "Fever Dream" },
            { 882,  "Darkwing" },
            { 1046, "Declassified" },
            { 1130, "Tooth Fairy" },
        }},

        { WEAPON_G3SG1, {
            { 0,    "Default" },
            { 6,    "Desert Storm" },
            { 27,   "Bone Mask" },
            { 46,   "Azure" },
            { 72,   "Safari Mesh" },
            { 73,   "Polar Camo" },
            { 84,   "Demeter" },
            { 187,  "Orange Kimono" },
            { 229,  "Stinger" },
            { 294,  "Flux" },
            { 382,  "Aurora" },
            { 438,  "Death Rattle" },
            { 640,  "The Executioner" },
            { 868,  "SC-1000" },
            { 1031, "Dream Glade" },
        }},

        { WEAPON_SCAR20, {
            { 0,    "Default" },
            { 11,   "Storm" },
            { 15,   "Contractor" },
            { 38,   "Carbon Fiber" },
            { 70,   "Crimson Web" },
            { 71,   "Blood in the Water" },
            { 103,  "Torn" },
            { 165,  "Cardboard" },
            { 262,  "Army Mesh" },
            { 288,  "Emerald" },
            { 312,  "Cyrex" },
            { 391,  "Emerald" },
            { 452,  "Shapemaster" },
            { 755,  "Broken Skull" },
            { 846,  "Fool" },
            { 1020, "Pulse" },
        }},

        // ════════════════════════════════════════════════════════════════
        // SMGs
        // ════════════════════════════════════════════════════════════════

        { WEAPON_MAC10, {
            { 0,    "Default" },
            { 17,   "Fall" },
            { 38,   "Silver" },
            { 42,   "Indigo" },
            { 72,   "Forest DDPAT" },
            { 98,   "Tatters" },
            { 157,  "Malachite" },
            { 169,  "Neon Rider" },
            { 175,  "Ultraviolet" },
            { 246,  "Amber Fade" },
            { 310,  "Nuclear Garden" },
            { 333,  "Commuter" },
            { 372,  "Heat" },
            { 387,  "Pulse" },
            { 433,  "Rangeen" },
            { 485,  "Lapis Gator" },
            { 543,  "Stygian" },
            { 597,  "Neon Rider" },
            { 649,  "Pipe Down" },
            { 862,  "Monkey Business" },
            { 967,  "Cyber Security" },
        }},

        { WEAPON_UMP45, {
            { 0,    "Default" },
            { 15,   "Corporal" },
            { 70,   "Crimson Web" },
            { 79,   "Arctic Wolf" },
            { 88,   "Indigo" },
            { 93,   "Primal Saber" },
            { 169,  "Delusion" },
            { 281,  "Grand Prix" },
            { 362,  "Scorched" },
            { 388,  "Riot" },
            { 437,  "Celestial" },
            { 440,  "Primal Saber" },
            { 488,  "FOIL" },
            { 526,  "Oscar" },
            { 646,  "Scaffold" },
            { 834,  "Metal Flowers" },
            { 870,  "Moonriser" },
            { 1045, "Plot Twist" },
        }},

        { WEAPON_MP9, {
            { 0,    "Default" },
            { 27,   "Blue Steel" },
            { 33,   "Hot Rod" },
            { 111,  "Airlock" },
            { 187,  "Bioleak" },
            { 262,  "Modest Threat" },
            { 329,  "Deadly Poison" },
            { 402,  "Hydra" },
            { 448,  "Goo" },
            { 549,  "High Noon" },
            { 603,  "Dark Water" },
            { 632,  "Music Player" },
            { 880,  "Set an Example" },
            { 1004, "Wild Lily" },
        }},

        { WEAPON_MP7, {
            { 0,    "Default" },
            { 15,   "Groundwater" },
            { 28,   "Whiteout" },
            { 113,  "Armor Core" },
            { 141,  "Forest DDPAT" },
            { 209,  "Akoben" },
            { 250,  "Fade" },
            { 280,  "Ocean Foam" },
            { 310,  "Skulls" },
            { 354,  "Gun Smoke" },
            { 423,  "Elite Build" },
            { 487,  "Asterion" },
            { 500,  "Impire" },
            { 538,  "Urban Hazard" },
            { 615,  "Nylon" },
            { 657,  "Cirrus" },
            { 810,  "Power Loader" },
            { 848,  "Bloodsport" },
            { 919,  "Phosphor" },
        }},

        { WEAPON_P90, {
            { 0,    "Default" },
            { 37,   "Cold Blooded" },
            { 111,  "Scorched" },
            { 169,  "Trigon" },
            { 175,  "Death by Kitty" },
            { 243,  "Emerald Dragon" },
            { 244,  "Death by Kitty" },
            { 262,  "Wolf Ruby" },
            { 341,  "Asteroid" },
            { 359,  "Ash Wood" },
            { 362,  "Leather" },
            { 382,  "Ventral" },
            { 422,  "Elite Build" },
            { 516,  "Shallow Grave" },
            { 673,  "Nebula Crusader" },
            { 836,  "Shallow Grave" },
            { 842,  "XS Rust" },
            { 861,  "Bloodsport" },
            { 950,  "Neo-Noir" },
            { 1023, "Facility Draft" },
        }},

        { WEAPON_MP5SD, {
            { 0,    "Default" },
            { 588,  "Kitbash" },
            { 617,  "Phantom" },
            { 649,  "Desert Strike" },
            { 710,  "Gauss" },
            { 805,  "Army Rebuild" },
            { 834,  "Leaded Glass" },
            { 921,  "Dirt Drop" },
            { 986,  "Bread & Hammer" },
            { 1045, "Oxide Blaze" },
            { 1075, "Liquidation" },
        }},

        { WEAPON_PPBIZON, {
            { 0,    "Default" },
            { 22,   "Rust Coat" },
            { 148,  "Sand Dashed" },
            { 149,  "Urban Perforated" },
            { 171,  "Carbon Fiber" },
            { 175,  "Night Ops" },
            { 236,  "Antique" },
            { 267,  "Rattler" },
            { 308,  "High Roller" },
            { 367,  "Facility" },
            { 423,  "Delusion" },
            { 460,  "Jungle Slipstream" },
            { 483,  "Bioleak" },
            { 642,  "Neonnm" },
            { 837,  "Rust Coat" },
            { 980,  "Lumen" },
        }},

        // ════════════════════════════════════════════════════════════════
        // SHOTGUNS
        // ════════════════════════════════════════════════════════════════

        { WEAPON_XM1014, {
            { 0,    "Default" },
            { 4,    "Bone Forged" },
            { 22,   "Blaze Orange" },
            { 42,   "Blue Spruce" },
            { 71,   "Blue Steel" },
            { 132,  "Oxide Blaze" },
            { 151,  "VariCamo" },
            { 166,  "Fall" },
            { 169,  "Trigon" },
            { 174,  "Scorched" },
            { 266,  "Red Python" },
            { 305,  "Trinity" },
            { 380,  "Scumbria" },
            { 557,  "Slipstream" },
            { 654,  "Oxide Blaze" },
            { 851,  "Wild Six" },
            { 920,  "Entombed" },
            { 1042, "XOXO" },
        }},

        { WEAPON_NOVA, {
            { 0,    "Default" },
            { 3,    "Walnut" },
            { 22,   "Candy Apple" },
            { 56,   "Modern Hunter" },
            { 77,   "Sand Dune" },
            { 98,   "Forest DDPAT" },
            { 164,  "Fall" },
            { 166,  "Radiation Hazard" },
            { 179,  "Green Apple" },
            { 214,  "Antique" },
            { 225,  "Graphite" },
            { 230,  "Walnut" },
            { 239,  "Martin" },
            { 249,  "Mandarin" },
            { 286,  "Toy Soldier" },
            { 356,  "Koi" },
            { 367,  "Ranger" },
            { 389,  "Hyper Beast" },
            { 484,  "Wood Fired" },
            { 537,  "Rust Coat" },
            { 637,  "Summit" },
            { 681,  "Tempest" },
            { 857,  "Space Lighting" },
            { 975,  "Hardy" },
            { 1041, "Clear Polymer" },
        }},

        { WEAPON_MAG7, {
            { 0,    "Default" },
            { 15,   "Silver" },
            { 34,   "Sand Dune" },
            { 39,   "Bulldozer" },
            { 66,   "Storm" },
            { 99,   "Sand Dune" },
            { 178,  "Heaven Guard" },
            { 198,  "Petroglyph" },
            { 262,  "Forest DDPAT" },
            { 288,  "Irradiated" },
            { 308,  "Carbonado" },
            { 471,  "Pronghorn" },
            { 493,  "Swag7" },
            { 535,  "Praetorian" },
            { 600,  "Coinage" },
            { 638,  "Industrial Cascade" },
            { 810,  "Heat" },
            { 854,  "Competitor" },
            { 904,  "Palladium" },
            { 1025, "Sonar" },
        }},

        { WEAPON_SAWEDOFF, {
            { 0,    "Default" },
            { 17,   "Forest DDPAT" },
            { 25,   "Forest DDPAT" },
            { 38,   "Oxide Blaze" },
            { 41,   "Snake Camo" },
            { 61,   "Black Silver" },
            { 100,  "Fall" },
            { 124,  "Urban DDPAT" },
            { 151,  "Forest DDPAT" },
            { 168,  "Fall" },
            { 171,  "Forest DDPAT" },
            { 214,  "Contrast Spray" },
            { 306,  "Hemorrhage" },
            { 390,  "Fubar" },
            { 401,  "Rust Coat" },
            { 473,  "Prike" },
            { 521,  "Bamboo" },
            { 638,  "Yorick" },
            { 729,  "Zander" },
            { 849,  "Bamboozle" },
        }},

        { WEAPON_NEGEV, {
            { 0,    "Default" },
            { 18,   "Anodized Navy" },
            { 39,   "Bulldozer" },
            { 72,   "Bone Mask" },
            { 75,   "Predator" },
            { 147,  "Mjölnir" },
            { 227,  "Mountain Storm" },
            { 256,  "Army Mesh" },
            { 279,  "Loudmouth" },
            { 285,  "Manufactured" },
            { 355,  "Man-o'-war" },
            { 369,  "Power Loader" },
            { 432,  "Neon Rider" },
            { 473,  "Dztec" },
            { 558,  "Aerial" },
            { 636,  "Disposal" },
            { 855,  "Prototype" },
            { 924,  "Uprising" },
            { 1048, "Drop Me" },
        }},

        { WEAPON_M249, {
            { 0,    "Default" },
            { 22,   "Blaze Orange" },
            { 71,   "Forest DDPAT" },
            { 99,   "Contrast" },
            { 147,  "Impact" },
            { 226,  "Boro" },
            { 252,  "Amber Stripe" },
            { 298,  "Magma" },
            { 362,  "Firefight" },
            { 407,  "Sun in Leo" },
            { 452,  "Petroglyph" },
            { 525,  "Dazzle" },
            { 636,  "Spectre" },
            { 837,  "Scorched" },
            { 1009, "Humidor" },
        }},

        // ════════════════════════════════════════════════════════════════
        // PISTOLS
        // ════════════════════════════════════════════════════════════════

        { WEAPON_DEAGLE, {
            { 0,    "Default" },
            { 5,    "Forest DDPAT" },
            { 12,   "Crimson Web" },
            { 17,   "Urban DDPAT" },
            { 37,   "Blaze" },
            { 40,   "Night" },
            { 61,   "Hypnotic" },
            { 90,   "Mudder" },
            { 185,  "Golden Koi" },
            { 231,  "Cobalt Disruption" },
            { 237,  "Urban Rubble" },
            { 248,  "Red Quartz" },
            { 273,  "Heirloom" },
            { 296,  "Meteorite" },
            { 328,  "Hand Cannon" },
            { 347,  "Pilot" },
            { 351,  "Conspiracy" },
            { 397,  "Naga" },
            { 425,  "Bronze Deco" },
            { 509,  "Corinthian" },
            { 527,  "Kumicho Dragon" },
            { 644,  "Conspiracy" },
            { 788,  "Code Red" },
            { 839,  "Printstream" },
            { 922,  "Mecha Industries" },
            { 975,  "Succubus" },
            { 1043, "Blue Ply" },
            { 1101, "Trigger Discipline" },
        }},

        { WEAPON_USP, {
            { 0,    "Default" },
            { 25,   "Forest Leaves" },
            { 60,   "Dark Water" },
            { 183,  "Overgrowth" },
            { 217,  "Blood Tiger" },
            { 221,  "Serum" },
            { 235,  "VariCamo" },
            { 236,  "Night Ops" },
            { 277,  "Stainless" },
            { 290,  "Guardian" },
            { 313,  "Orion" },
            { 318,  "Road Rash" },
            { 332,  "Cortex" },
            { 339,  "Caiman" },
            { 364,  "Business Class" },
            { 454,  "Para Green" },
            { 489,  "Torque" },
            { 504,  "Neo-Noir" },
            { 658,  "Printstream" },
            { 755,  "Kill Confirmed" },
            { 832,  "Blueprint" },
            { 886,  "Monster Mashup" },
            { 973,  "Copper" },
            { 1028, "Canyon" },
            { 1063, "Black Lotus" },
            { 1133, "Ticket to Hell" },
        }},

        { WEAPON_GLOCK, {
            { 0,    "Default" },
            { 2,    "Groundwater" },
            { 3,    "Candy Apple" },
            { 38,   "Fade" },
            { 40,   "Night" },
            { 48,   "Dragon Tattoo" },
            { 99,   "Brass" },
            { 159,  "Steel Disruption" },
            { 208,  "Blue Fissure" },
            { 230,  "Wasteland Rebel" },
            { 278,  "Death Rattle" },
            { 292,  "Wasteland Rebel" },
            { 353,  "Water Elemental" },
            { 367,  "Reactor" },
            { 381,  "Grinder" },
            { 399,  "Catacombs" },
            { 437,  "Twilight Galaxy" },
            { 479,  "Bunsen Burner" },
            { 495,  "Wraiths" },
            { 532,  "Royal Legion" },
            { 586,  "Gamma Doppler" },
            { 799,  "Water Elemental" },
            { 842,  "Bullet Queen" },
            { 917,  "Oxide Blaze" },
            { 959,  "Neo-Noir" },
            { 1041, "Vogue" },
            { 1099, "Clear Water" },
            { 1162, "Wasteland Rebel" },
        }},

        { WEAPON_P250, {
            { 0,    "Default" },
            { 2,    "Birchwood" },
            { 3,    "Sand Dune" },
            { 17,   "Forest DDPAT" },
            { 22,   "Gunsmoke" },
            { 35,   "Sand Dune" },
            { 59,   "Hive" },
            { 133,  "Mehndi" },
            { 162,  "Undertow" },
            { 164,  "Steel Disruption" },
            { 182,  "Metallic" },
            { 258,  "Asiimov" },
            { 270,  "Franklin" },
            { 295,  "Muertos" },
            { 358,  "Cartel" },
            { 388,  "Hemoglobin" },
            { 448,  "Contamination" },
            { 550,  "Nuclear Threat" },
            { 637,  "Ripple" },
            { 680,  "Drowning" },
            { 839,  "Kill Confirmed" },
            { 870,  "Forest Green" },
            { 953,  "Valence" },
            { 1013, "Selena" },
            { 1059, "Cassette" },
        }},

        { WEAPON_TEC9, {
            { 0,    "Default" },
            { 2,    "Forest DDPAT" },
            { 11,   "Groundwater" },
            { 36,   "Brass" },
            { 43,   "Tornado" },
            { 69,   "Oxide Blaze" },
            { 101,  "Urban DDPAT" },
            { 158,  "Nuclear Threat" },
            { 207,  "Red Quartz" },
            { 252,  "Stainless" },
            { 272,  "Havoc" },
            { 320,  "Isaac" },
            { 364,  "Titanium Bit" },
            { 401,  "Bamboo Forest" },
            { 432,  "Groundwater" },
            { 463,  "Jambiya" },
            { 479,  "Fuel Injector" },
            { 539,  "Re-Entry" },
            { 653,  "Reactor" },
            { 673,  "Fubar" },
            { 822,  "Oni" },
            { 878,  "Blast" },
            { 941,  "Side Scope" },
            { 1039, "Decimator" },
            { 1073, "Noir" },
            { 1130, "Neon Kimono" },
        }},

        { WEAPON_FIVESEVEN, {
            { 0,    "Default" },
            { 3,    "Case Hardened" },
            { 4,    "Forest Night" },
            { 44,   "Forest Night" },
            { 45,   "Hot Shot" },
            { 46,   "Fall" },
            { 77,   "Neon Kimono" },
            { 78,   "Forest DDPAT" },
            { 85,   "Orange Peel" },
            { 151,  "Fouquet" },
            { 174,  "Case Hardened" },
            { 210,  "Nitro" },
            { 252,  "Case Hardened" },
            { 262,  "Nostalgia" },
            { 274,  "Felon" },
            { 332,  "Monkey Business" },
            { 352,  "Hot Shot" },
            { 387,  "Checked" },
            { 464,  "Triumvirate" },
            { 510,  "Neon Kimono" },
            { 522,  "Urban Hazard" },
            { 600,  "Superconductor" },
            { 694,  "Scumbria" },
            { 845,  "Capillary" },
            { 893,  "Angry Mob" },
            { 963,  "Lava Flow" },
            { 1035, "Scrawl" },
            { 1071, "Berries And Cherries" },
        }},

        { WEAPON_ELITE, {
            { 0,    "Default" },
            { 3,    "Boreal Forest" },
            { 22,   "Colon" },
            { 28,   "Midnight Storm" },
            { 36,   "Urban DDPAT" },
            { 43,   "Colony" },
            { 46,   "Heist" },
            { 72,   "Case Hardened" },
            { 91,   "Storm" },
            { 150,  "Demolition" },
            { 180,  "Urban Polymer" },
            { 226,  "Hand Cannon" },
            { 249,  "Dualing Dragons" },
            { 261,  "Ventilators" },
            { 330,  "Cobra" },
            { 396,  "Urban Shuffle" },
            { 447,  "Cartel" },
            { 458,  "Royal Consorts" },
            { 491,  "Glock Grinder" },
            { 528,  "De矣luge" },
            { 659,  "Black Limba" },
            { 669,  "Tower Seven" },
            { 846,  "Declassified" },
            { 888,  "Ventilator" },
        }},

        { WEAPON_CZ75, {
            { 0,    "Default" },
            { 32,   "Crimson Web" },
            { 43,   "Hexane" },
            { 63,   "Jungle" },
            { 64,   "Nitro" },
            { 79,   "Yellow Jacket" },
            { 83,   "Anodized Gunmetal" },
            { 98,   "Tigris" },
            { 143,  "Tuxedo" },
            { 169,  "Nitro" },
            { 202,  "Red Quartz" },
            { 266,  "Xiangliu" },
            { 322,  "Victoria" },
            { 334,  "Tigris" },
            { 350,  "Imprint" },
            { 417,  "The Fuchsia Is Now" },
            { 453,  "Nascus" },
            { 476,  "Tigris" },
            { 543,  "Polymer" },
            { 602,  "The Fuchsia Is Now" },
            { 638,  "Cobalt" },
            { 643,  "Nascus" },
            { 822,  "Eco" },
            { 856,  "Akoben" },
            { 881,  "Jungle Slipstream" },
            { 918,  "Tiger Tooth" },
            { 962,  "Racer" },
        }},

        { WEAPON_REVOLVER, {
            { 0,    "Default" },
            { 12,   "Crimson Web" },
            { 27,   "Bone Mask" },
            { 246,  "Amber Fade" },
            { 260,  "Fade" },
            { 343,  "Reboot" },
            { 522,  "Fade" },
            { 675,  "Reboot" },
            { 851,  "Llama Cannon" },
            { 971,  "Mogul" },
        }},

        { WEAPON_P2000, {
            { 0,    "Default" },
            { 2,    "Forest DDPAT" },
            { 3,    "Sand Dune" },
            { 18,   "Anodized Navy" },
            { 21,   "Drop Shot" },
            { 38,   "Ocean Foam" },
            { 44,   "Scalper" },
            { 50,   "Grassland" },
            { 72,   "Camouflage" },
            { 73,   "Forest DDPAT" },
            { 97,   "Silver" },
            { 144,  "Facility" },
            { 154,  "Wooden" },
            { 180,  "Camouflage" },
            { 219,  "Imperial Dragon" },
            { 246,  "Chainmail" },
            { 255,  "Imperial Dragon" },
            { 280,  "Fire Elemental" },
            { 338,  "Asterion" },
            { 345,  "Corticera" },
            { 389,  "Red FragCam" },
            { 400,  "Urban Hazard" },
            { 485,  "Ocean Foam" },
            { 489,  "Contour" },
            { 540,  "Teal Blast" },
            { 591,  "Oxide Blaze" },
            { 635,  "Neo-Noir" },
            { 702,  "Exotic Rajah" },
            { 801,  "Urban DDPAT" },
            { 952,  "Viper" },
            { 1041, "Gamma Doppler" },
            { 1132, "Fade" },
        }},
    };
    return s;
}

// Legacy accessor — returns a flat list of all popular skins (for backward compat).
inline const std::vector<SkinEntry>& PopularSkins() {
    static const std::vector<SkinEntry> s = {
        { 0,    "Default" },
        // AK-47
        { 180,  "Redline" },
        { 302,  "Vulcan" },
        { 44,   "Red Laminate" },
        { 144,  "Fire Serpent" },
        { 747,  "Neon Rider" },
        { 801,  "The Empress" },
        { 506,  "Cartel" },
        { 639,  "Frontside Misty" },
        { 878,  "Ice Coaled" },
        // AWP
        { 38,   "Dragon Lore" },
        { 51,   "Asiimov" },
        { 259,  "Medusa" },
        { 344,  "Hyper Beast" },
        { 475,  "Wildfire" },
        { 662,  "Fade" },
        { 837,  "Neo-Noir" },
        { 898,  "Containment Breach" },
        // M4A4
        { 309,  "Howl" },
        { 388,  "Desolate Space" },
        { 488,  "Buzz Kill" },
        { 730,  "Neo-Noir" },
        { 811,  "In Living Color" },
        // M4A1-S
        { 430,  "Hyper Beast" },
        { 587,  "Chantico's Fire" },
        { 757,  "Decimator" },
        { 897,  "Printstream" },
        // USP-S
        { 25,   "Kill Confirmed" },
        { 332,  "Cortex" },
        { 504,  "Neo-Noir" },
        { 658,  "Printstream" },
        // Glock-18
        { 38,   "Fade" },
        { 292,  "Wasteland Rebel" },
        { 586,  "Gamma Doppler" },
        { 799,  "Water Elemental" },
        // knives
        { 568,  "Fade" },
        { 569,  "Marble Fade" },
        { 570,  "Doppler" },
        { 571,  "Tiger Tooth" },
        { 572,  "Crimson Web" },
        { 578,  "Slaughter" },
        { 600,  "Lore" },
        { 752,  "Case Hardened" },
        { 1132, "Autotronic" },
        { 1133, "Blue Steel" },
        { 1134, "Rust Coat" },
        { 1135, "Stained" },
    };
    return s;
}

// Wear display names.
inline const char* WearName(float wear) {
    if (wear < 0.07f) return "Factory New";
    if (wear < 0.15f) return "Minimal Wear";
    if (wear < 0.38f) return "Field-Tested";
    if (wear < 0.45f) return "Well-Worn";
    return "Battle-Scarred";
}

} // namespace SkinDB
