name: Windows build

on:
  workflow_dispatch:
  push:
    branches: [main, omarchy-port]
    paths:
      - '**/*.sln'
      - '**/*.vcxproj'
      - '**/*.cpp'
      - '**/*.hpp'
      - '**/*.c'
      - '**/*.h'
      - 'scripts/build.bat'
      - '.github/workflows/auto_build.yml'
  pull_request:
    paths:
      - '**/*.sln'
      - '**/*.vcxproj'
      - '**/*.cpp'
      - '**/*.hpp'
      - '**/*.c'
      - '**/*.h'
      - 'scripts/build.bat'
      - '.github/workflows/auto_build.yml'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v3

    - name: Build solution
      env:
        VCPKG_ROOT: ${{ env.VCPKG_ROOT }}
      run: msbuild sourcesight.sln /p:Configuration=Release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v7
      with:
        name: sourcesight-windows
        path: |
          x64/Release/*
