name: Typo check
on:
  push:
    branches: [main, omarchy-port]
  pull_request:

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Check spelling
      uses: crate-ci/typos@v1.49.0
      with:
        files: ./src ./scripts ./.github ./README.md ./CONTRIBUTING.md ./SECURITY.md
        config: .github/typos.toml
